### ISSUE TITLE
Test failing (segfault) after PR120

### ISSUE THREAD

**Issue by flikka** [OPM/opm-material#123] opened 2016-02-12 07:18 UTC
After https://github.com/OPM/opm-material/pull/120 a test fails, thus stopping the OPM build pipeline on Jenkins. See https://ci.opm-project.org/job/opm-material/964/

**Comment by atgeirr** [comment] 2016-02-12 09:14
Not able to reproduce on my system (Mac OS X, clang) unfortunately.

**Comment by flikka** [comment] 2016-02-12 09:48
Ok, I see. It fails both on the Travis build, and on our Jenkins in the
Cloud. Perhaps Andreas has an idea.

On Fri, Feb 12, 2016 at 10:14 AM, Atgeirr Flø Rasmussen <
notifications@github.com> wrote:

> Not able to reproduce on my system (Mac OS X, clang) unfortunately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OPM/opm-material/issues/123#issuecomment-183245022>.
>



-- 
Hilsen
Kristian Flikka
mobil: 952 24 952

**Comment by andlaus** [comment] 2016-02-12 10:58
Actually, I don't anything concrete idea because it also works on my system. #120 changes the case Evaluation ->  Evaluation case of the `Toolbox::toLhs()` method to just return a reference to the object which is put into it, so it may cause problems if the object passed to `toLhs()` goes out of scope and the result is used after that. finding such issues without being able to reproduce the error is basically impossible, though. (can I get SSH access to the jenkins server?)

**Comment by alfbr** [comment] 2016-02-12 11:20
@andlaus have you tested with gcc?

**Comment by andlaus** [comment] 2016-02-12 11:43
yes (5.2.1 to be precise)

but I guess the problem is the weird const-references-to-temporary-objects issue. the problem is that this is quite subtle and requires deeper c++ template-foo to fix. I'm working on it...

**Closed** 2016-02-12 18:07 UTC

**Comment by andlaus** [comment] 2016-02-12 18:24
please re-open this issue if #125 did not fix it. (BTW: github seems to have a new feature "try to understand what the comments in merged PRs say and close issues if you think that they appear to be fixed". to stupit people like me this seems to be quite a bit of voodoo, but github seems to have smart employees ;))
